easy_admin:
    site_name: 'SYMFONY'
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
            controller: App\Controller\Admin\ProductController
            label: 'Продукты'
            list:
                title: 'Список продуктов'
                fields:
                    - id
                    - { property: 'title', label: 'Заголовок', type: 'string' }
                    - { property: 'image.path', label: 'Картинка', type: 'image', base_path: '/upload/product/' }
                actions:
                    - { name: 'new', label: 'Добавить продукт' }
            form:
                fields:
                    - { property: 'title', label: 'Заголовок', type: 'text' }
                    - { property: 'description', label: 'Описание', type: 'textarea' }
                    - { property: 'image', label: 'Картинка', type: 'file' }
#        - App\Entity\Category
#        - App\Entity\User
